# Site settings
title: ScatterLab
email: hello@scatterlab.org
description: scatterlab.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "scatterlab.org" # the base hostname & protocol for your site
twitter_username: scatterlab
github_username:  scatterlaboratory

# Build settings
markdown: kramdown
